name: Python Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Copy Code To Test DIR
      # Build your program with the given configuration
      run: cp -r ${{github.workspace}}/src/* ${{github.workspace}}/test

    - name: Python Unit Test
      # Build your program with the given configuration
      run: cd ${{github.workspace}};python -m unittest discover -s ./test -p 'test_*.py' --verbose
      
